// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_image_5fmsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_image_5fmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_image_5fmsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_image_5fmsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_image_5fmsg_2eproto;
namespace image_msg {
class bbox;
class bboxDefaultTypeInternal;
extern bboxDefaultTypeInternal _bbox_default_instance_;
class detections;
class detectionsDefaultTypeInternal;
extern detectionsDefaultTypeInternal _detections_default_instance_;
class image;
class imageDefaultTypeInternal;
extern imageDefaultTypeInternal _image_default_instance_;
class image_buf;
class image_bufDefaultTypeInternal;
extern image_bufDefaultTypeInternal _image_buf_default_instance_;
class one_detection;
class one_detectionDefaultTypeInternal;
extern one_detectionDefaultTypeInternal _one_detection_default_instance_;
}  // namespace image_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::image_msg::bbox* Arena::CreateMaybeMessage<::image_msg::bbox>(Arena*);
template<> ::image_msg::detections* Arena::CreateMaybeMessage<::image_msg::detections>(Arena*);
template<> ::image_msg::image* Arena::CreateMaybeMessage<::image_msg::image>(Arena*);
template<> ::image_msg::image_buf* Arena::CreateMaybeMessage<::image_msg::image_buf>(Arena*);
template<> ::image_msg::one_detection* Arena::CreateMaybeMessage<::image_msg::one_detection>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace image_msg {

// ===================================================================

class image PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:image_msg.image) */ {
 public:
  inline image() : image(nullptr) {};
  virtual ~image();

  image(const image& from);
  image(image&& from) noexcept
    : image() {
    *this = ::std::move(from);
  }

  inline image& operator=(const image& from) {
    CopyFrom(from);
    return *this;
  }
  inline image& operator=(image&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const image& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const image* internal_default_instance() {
    return reinterpret_cast<const image*>(
               &_image_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(image& a, image& b) {
    a.Swap(&b);
  }
  inline void Swap(image* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(image* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline image* New() const final {
    return CreateMaybeMessage<image>(nullptr);
  }

  image* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<image>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const image& from);
  void MergeFrom(const image& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(image* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "image_msg.image";
  }
  protected:
  explicit image(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_5fmsg_2eproto);
    return ::descriptor_table_image_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMatDataFieldNumber = 6,
    kTimeStampFieldNumber = 1,
    kHeightFieldNumber = 2,
    kWidthFieldNumber = 3,
    kChannelFieldNumber = 4,
    kSizeFieldNumber = 5,
  };
  // bytes mat_data = 6;
  void clear_mat_data();
  const std::string& mat_data() const;
  void set_mat_data(const std::string& value);
  void set_mat_data(std::string&& value);
  void set_mat_data(const char* value);
  void set_mat_data(const void* value, size_t size);
  std::string* mutable_mat_data();
  std::string* release_mat_data();
  void set_allocated_mat_data(std::string* mat_data);
  private:
  const std::string& _internal_mat_data() const;
  void _internal_set_mat_data(const std::string& value);
  std::string* _internal_mutable_mat_data();
  public:

  // double time_stamp = 1;
  void clear_time_stamp();
  double time_stamp() const;
  void set_time_stamp(double value);
  private:
  double _internal_time_stamp() const;
  void _internal_set_time_stamp(double value);
  public:

  // int32 height = 2;
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::int32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 width = 3;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::int32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 channel = 4;
  void clear_channel();
  ::PROTOBUF_NAMESPACE_ID::int32 channel() const;
  void set_channel(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_channel() const;
  void _internal_set_channel(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 size = 5;
  void clear_size();
  ::PROTOBUF_NAMESPACE_ID::int32 size() const;
  void set_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_size() const;
  void _internal_set_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:image_msg.image)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mat_data_;
  double time_stamp_;
  ::PROTOBUF_NAMESPACE_ID::int32 height_;
  ::PROTOBUF_NAMESPACE_ID::int32 width_;
  ::PROTOBUF_NAMESPACE_ID::int32 channel_;
  ::PROTOBUF_NAMESPACE_ID::int32 size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_image_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class bbox PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:image_msg.bbox) */ {
 public:
  inline bbox() : bbox(nullptr) {};
  virtual ~bbox();

  bbox(const bbox& from);
  bbox(bbox&& from) noexcept
    : bbox() {
    *this = ::std::move(from);
  }

  inline bbox& operator=(const bbox& from) {
    CopyFrom(from);
    return *this;
  }
  inline bbox& operator=(bbox&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const bbox& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const bbox* internal_default_instance() {
    return reinterpret_cast<const bbox*>(
               &_bbox_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(bbox& a, bbox& b) {
    a.Swap(&b);
  }
  inline void Swap(bbox* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(bbox* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline bbox* New() const final {
    return CreateMaybeMessage<bbox>(nullptr);
  }

  bbox* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<bbox>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const bbox& from);
  void MergeFrom(const bbox& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(bbox* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "image_msg.bbox";
  }
  protected:
  explicit bbox(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_5fmsg_2eproto);
    return ::descriptor_table_image_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXLeftTopFieldNumber = 1,
    kYLeftTopFieldNumber = 2,
    kXRightBottomFieldNumber = 3,
    kYRightBottomFieldNumber = 4,
  };
  // int32 x_left_top = 1;
  void clear_x_left_top();
  ::PROTOBUF_NAMESPACE_ID::int32 x_left_top() const;
  void set_x_left_top(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x_left_top() const;
  void _internal_set_x_left_top(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y_left_top = 2;
  void clear_y_left_top();
  ::PROTOBUF_NAMESPACE_ID::int32 y_left_top() const;
  void set_y_left_top(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y_left_top() const;
  void _internal_set_y_left_top(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 x_right_bottom = 3;
  void clear_x_right_bottom();
  ::PROTOBUF_NAMESPACE_ID::int32 x_right_bottom() const;
  void set_x_right_bottom(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x_right_bottom() const;
  void _internal_set_x_right_bottom(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y_right_bottom = 4;
  void clear_y_right_bottom();
  ::PROTOBUF_NAMESPACE_ID::int32 y_right_bottom() const;
  void set_y_right_bottom(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y_right_bottom() const;
  void _internal_set_y_right_bottom(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:image_msg.bbox)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_left_top_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_left_top_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_right_bottom_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_right_bottom_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_image_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class one_detection PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:image_msg.one_detection) */ {
 public:
  inline one_detection() : one_detection(nullptr) {};
  virtual ~one_detection();

  one_detection(const one_detection& from);
  one_detection(one_detection&& from) noexcept
    : one_detection() {
    *this = ::std::move(from);
  }

  inline one_detection& operator=(const one_detection& from) {
    CopyFrom(from);
    return *this;
  }
  inline one_detection& operator=(one_detection&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const one_detection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const one_detection* internal_default_instance() {
    return reinterpret_cast<const one_detection*>(
               &_one_detection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(one_detection& a, one_detection& b) {
    a.Swap(&b);
  }
  inline void Swap(one_detection* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(one_detection* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline one_detection* New() const final {
    return CreateMaybeMessage<one_detection>(nullptr);
  }

  one_detection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<one_detection>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const one_detection& from);
  void MergeFrom(const one_detection& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(one_detection* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "image_msg.one_detection";
  }
  protected:
  explicit one_detection(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_5fmsg_2eproto);
    return ::descriptor_table_image_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOneBboxFieldNumber = 3,
    kConfindeceFieldNumber = 1,
    kThisClassFieldNumber = 2,
  };
  // .image_msg.bbox one_bbox = 3;
  bool has_one_bbox() const;
  private:
  bool _internal_has_one_bbox() const;
  public:
  void clear_one_bbox();
  const ::image_msg::bbox& one_bbox() const;
  ::image_msg::bbox* release_one_bbox();
  ::image_msg::bbox* mutable_one_bbox();
  void set_allocated_one_bbox(::image_msg::bbox* one_bbox);
  private:
  const ::image_msg::bbox& _internal_one_bbox() const;
  ::image_msg::bbox* _internal_mutable_one_bbox();
  public:
  void unsafe_arena_set_allocated_one_bbox(
      ::image_msg::bbox* one_bbox);
  ::image_msg::bbox* unsafe_arena_release_one_bbox();

  // float confindece = 1;
  void clear_confindece();
  float confindece() const;
  void set_confindece(float value);
  private:
  float _internal_confindece() const;
  void _internal_set_confindece(float value);
  public:

  // int32 this_class = 2;
  void clear_this_class();
  ::PROTOBUF_NAMESPACE_ID::int32 this_class() const;
  void set_this_class(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_this_class() const;
  void _internal_set_this_class(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:image_msg.one_detection)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::image_msg::bbox* one_bbox_;
  float confindece_;
  ::PROTOBUF_NAMESPACE_ID::int32 this_class_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_image_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class detections PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:image_msg.detections) */ {
 public:
  inline detections() : detections(nullptr) {};
  virtual ~detections();

  detections(const detections& from);
  detections(detections&& from) noexcept
    : detections() {
    *this = ::std::move(from);
  }

  inline detections& operator=(const detections& from) {
    CopyFrom(from);
    return *this;
  }
  inline detections& operator=(detections&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const detections& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const detections* internal_default_instance() {
    return reinterpret_cast<const detections*>(
               &_detections_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(detections& a, detections& b) {
    a.Swap(&b);
  }
  inline void Swap(detections* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(detections* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline detections* New() const final {
    return CreateMaybeMessage<detections>(nullptr);
  }

  detections* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<detections>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const detections& from);
  void MergeFrom(const detections& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(detections* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "image_msg.detections";
  }
  protected:
  explicit detections(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_5fmsg_2eproto);
    return ::descriptor_table_image_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageFieldNumber = 2,
    kDetectionFieldNumber = 3,
    kDetectedFlagFieldNumber = 1,
  };
  // repeated .image_msg.image image_ = 2;
  int image__size() const;
  private:
  int _internal_image__size() const;
  public:
  void clear_image_();
  ::image_msg::image* mutable_image_(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image >*
      mutable_image_();
  private:
  const ::image_msg::image& _internal_image_(int index) const;
  ::image_msg::image* _internal_add_image_();
  public:
  const ::image_msg::image& image_(int index) const;
  ::image_msg::image* add_image_();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image >&
      image_() const;

  // repeated .image_msg.one_detection detection = 3;
  int detection_size() const;
  private:
  int _internal_detection_size() const;
  public:
  void clear_detection();
  ::image_msg::one_detection* mutable_detection(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::one_detection >*
      mutable_detection();
  private:
  const ::image_msg::one_detection& _internal_detection(int index) const;
  ::image_msg::one_detection* _internal_add_detection();
  public:
  const ::image_msg::one_detection& detection(int index) const;
  ::image_msg::one_detection* add_detection();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::one_detection >&
      detection() const;

  // bool detected_flag = 1;
  void clear_detected_flag();
  bool detected_flag() const;
  void set_detected_flag(bool value);
  private:
  bool _internal_detected_flag() const;
  void _internal_set_detected_flag(bool value);
  public:

  // @@protoc_insertion_point(class_scope:image_msg.detections)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image > image__;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::one_detection > detection_;
  bool detected_flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_image_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class image_buf PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:image_msg.image_buf) */ {
 public:
  inline image_buf() : image_buf(nullptr) {};
  virtual ~image_buf();

  image_buf(const image_buf& from);
  image_buf(image_buf&& from) noexcept
    : image_buf() {
    *this = ::std::move(from);
  }

  inline image_buf& operator=(const image_buf& from) {
    CopyFrom(from);
    return *this;
  }
  inline image_buf& operator=(image_buf&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const image_buf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const image_buf* internal_default_instance() {
    return reinterpret_cast<const image_buf*>(
               &_image_buf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(image_buf& a, image_buf& b) {
    a.Swap(&b);
  }
  inline void Swap(image_buf* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(image_buf* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline image_buf* New() const final {
    return CreateMaybeMessage<image_buf>(nullptr);
  }

  image_buf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<image_buf>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const image_buf& from);
  void MergeFrom(const image_buf& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(image_buf* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "image_msg.image_buf";
  }
  protected:
  explicit image_buf(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_5fmsg_2eproto);
    return ::descriptor_table_image_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageFieldNumber = 1,
  };
  // repeated .image_msg.image image_ = 1;
  int image__size() const;
  private:
  int _internal_image__size() const;
  public:
  void clear_image_();
  ::image_msg::image* mutable_image_(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image >*
      mutable_image_();
  private:
  const ::image_msg::image& _internal_image_(int index) const;
  ::image_msg::image* _internal_add_image_();
  public:
  const ::image_msg::image& image_(int index) const;
  ::image_msg::image* add_image_();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image >&
      image_() const;

  // @@protoc_insertion_point(class_scope:image_msg.image_buf)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image > image__;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_image_5fmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// image

// double time_stamp = 1;
inline void image::clear_time_stamp() {
  time_stamp_ = 0;
}
inline double image::_internal_time_stamp() const {
  return time_stamp_;
}
inline double image::time_stamp() const {
  // @@protoc_insertion_point(field_get:image_msg.image.time_stamp)
  return _internal_time_stamp();
}
inline void image::_internal_set_time_stamp(double value) {
  
  time_stamp_ = value;
}
inline void image::set_time_stamp(double value) {
  _internal_set_time_stamp(value);
  // @@protoc_insertion_point(field_set:image_msg.image.time_stamp)
}

// int32 height = 2;
inline void image::clear_height() {
  height_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 image::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 image::height() const {
  // @@protoc_insertion_point(field_get:image_msg.image.height)
  return _internal_height();
}
inline void image::_internal_set_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  height_ = value;
}
inline void image::set_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:image_msg.image.height)
}

// int32 width = 3;
inline void image::clear_width() {
  width_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 image::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 image::width() const {
  // @@protoc_insertion_point(field_get:image_msg.image.width)
  return _internal_width();
}
inline void image::_internal_set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  width_ = value;
}
inline void image::set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:image_msg.image.width)
}

// int32 channel = 4;
inline void image::clear_channel() {
  channel_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 image::_internal_channel() const {
  return channel_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 image::channel() const {
  // @@protoc_insertion_point(field_get:image_msg.image.channel)
  return _internal_channel();
}
inline void image::_internal_set_channel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  channel_ = value;
}
inline void image::set_channel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:image_msg.image.channel)
}

// int32 size = 5;
inline void image::clear_size() {
  size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 image::_internal_size() const {
  return size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 image::size() const {
  // @@protoc_insertion_point(field_get:image_msg.image.size)
  return _internal_size();
}
inline void image::_internal_set_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  size_ = value;
}
inline void image::set_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:image_msg.image.size)
}

// bytes mat_data = 6;
inline void image::clear_mat_data() {
  mat_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& image::mat_data() const {
  // @@protoc_insertion_point(field_get:image_msg.image.mat_data)
  return _internal_mat_data();
}
inline void image::set_mat_data(const std::string& value) {
  _internal_set_mat_data(value);
  // @@protoc_insertion_point(field_set:image_msg.image.mat_data)
}
inline std::string* image::mutable_mat_data() {
  // @@protoc_insertion_point(field_mutable:image_msg.image.mat_data)
  return _internal_mutable_mat_data();
}
inline const std::string& image::_internal_mat_data() const {
  return mat_data_.Get();
}
inline void image::_internal_set_mat_data(const std::string& value) {
  
  mat_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void image::set_mat_data(std::string&& value) {
  
  mat_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:image_msg.image.mat_data)
}
inline void image::set_mat_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mat_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:image_msg.image.mat_data)
}
inline void image::set_mat_data(const void* value,
    size_t size) {
  
  mat_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:image_msg.image.mat_data)
}
inline std::string* image::_internal_mutable_mat_data() {
  
  return mat_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* image::release_mat_data() {
  // @@protoc_insertion_point(field_release:image_msg.image.mat_data)
  return mat_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void image::set_allocated_mat_data(std::string* mat_data) {
  if (mat_data != nullptr) {
    
  } else {
    
  }
  mat_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mat_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:image_msg.image.mat_data)
}

// -------------------------------------------------------------------

// bbox

// int32 x_left_top = 1;
inline void bbox::clear_x_left_top() {
  x_left_top_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 bbox::_internal_x_left_top() const {
  return x_left_top_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 bbox::x_left_top() const {
  // @@protoc_insertion_point(field_get:image_msg.bbox.x_left_top)
  return _internal_x_left_top();
}
inline void bbox::_internal_set_x_left_top(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_left_top_ = value;
}
inline void bbox::set_x_left_top(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x_left_top(value);
  // @@protoc_insertion_point(field_set:image_msg.bbox.x_left_top)
}

// int32 y_left_top = 2;
inline void bbox::clear_y_left_top() {
  y_left_top_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 bbox::_internal_y_left_top() const {
  return y_left_top_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 bbox::y_left_top() const {
  // @@protoc_insertion_point(field_get:image_msg.bbox.y_left_top)
  return _internal_y_left_top();
}
inline void bbox::_internal_set_y_left_top(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_left_top_ = value;
}
inline void bbox::set_y_left_top(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y_left_top(value);
  // @@protoc_insertion_point(field_set:image_msg.bbox.y_left_top)
}

// int32 x_right_bottom = 3;
inline void bbox::clear_x_right_bottom() {
  x_right_bottom_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 bbox::_internal_x_right_bottom() const {
  return x_right_bottom_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 bbox::x_right_bottom() const {
  // @@protoc_insertion_point(field_get:image_msg.bbox.x_right_bottom)
  return _internal_x_right_bottom();
}
inline void bbox::_internal_set_x_right_bottom(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_right_bottom_ = value;
}
inline void bbox::set_x_right_bottom(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x_right_bottom(value);
  // @@protoc_insertion_point(field_set:image_msg.bbox.x_right_bottom)
}

// int32 y_right_bottom = 4;
inline void bbox::clear_y_right_bottom() {
  y_right_bottom_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 bbox::_internal_y_right_bottom() const {
  return y_right_bottom_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 bbox::y_right_bottom() const {
  // @@protoc_insertion_point(field_get:image_msg.bbox.y_right_bottom)
  return _internal_y_right_bottom();
}
inline void bbox::_internal_set_y_right_bottom(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_right_bottom_ = value;
}
inline void bbox::set_y_right_bottom(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y_right_bottom(value);
  // @@protoc_insertion_point(field_set:image_msg.bbox.y_right_bottom)
}

// -------------------------------------------------------------------

// one_detection

// float confindece = 1;
inline void one_detection::clear_confindece() {
  confindece_ = 0;
}
inline float one_detection::_internal_confindece() const {
  return confindece_;
}
inline float one_detection::confindece() const {
  // @@protoc_insertion_point(field_get:image_msg.one_detection.confindece)
  return _internal_confindece();
}
inline void one_detection::_internal_set_confindece(float value) {
  
  confindece_ = value;
}
inline void one_detection::set_confindece(float value) {
  _internal_set_confindece(value);
  // @@protoc_insertion_point(field_set:image_msg.one_detection.confindece)
}

// int32 this_class = 2;
inline void one_detection::clear_this_class() {
  this_class_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 one_detection::_internal_this_class() const {
  return this_class_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 one_detection::this_class() const {
  // @@protoc_insertion_point(field_get:image_msg.one_detection.this_class)
  return _internal_this_class();
}
inline void one_detection::_internal_set_this_class(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  this_class_ = value;
}
inline void one_detection::set_this_class(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_this_class(value);
  // @@protoc_insertion_point(field_set:image_msg.one_detection.this_class)
}

// .image_msg.bbox one_bbox = 3;
inline bool one_detection::_internal_has_one_bbox() const {
  return this != internal_default_instance() && one_bbox_ != nullptr;
}
inline bool one_detection::has_one_bbox() const {
  return _internal_has_one_bbox();
}
inline void one_detection::clear_one_bbox() {
  if (GetArena() == nullptr && one_bbox_ != nullptr) {
    delete one_bbox_;
  }
  one_bbox_ = nullptr;
}
inline const ::image_msg::bbox& one_detection::_internal_one_bbox() const {
  const ::image_msg::bbox* p = one_bbox_;
  return p != nullptr ? *p : *reinterpret_cast<const ::image_msg::bbox*>(
      &::image_msg::_bbox_default_instance_);
}
inline const ::image_msg::bbox& one_detection::one_bbox() const {
  // @@protoc_insertion_point(field_get:image_msg.one_detection.one_bbox)
  return _internal_one_bbox();
}
inline void one_detection::unsafe_arena_set_allocated_one_bbox(
    ::image_msg::bbox* one_bbox) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(one_bbox_);
  }
  one_bbox_ = one_bbox;
  if (one_bbox) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:image_msg.one_detection.one_bbox)
}
inline ::image_msg::bbox* one_detection::release_one_bbox() {
  
  ::image_msg::bbox* temp = one_bbox_;
  one_bbox_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::image_msg::bbox* one_detection::unsafe_arena_release_one_bbox() {
  // @@protoc_insertion_point(field_release:image_msg.one_detection.one_bbox)
  
  ::image_msg::bbox* temp = one_bbox_;
  one_bbox_ = nullptr;
  return temp;
}
inline ::image_msg::bbox* one_detection::_internal_mutable_one_bbox() {
  
  if (one_bbox_ == nullptr) {
    auto* p = CreateMaybeMessage<::image_msg::bbox>(GetArena());
    one_bbox_ = p;
  }
  return one_bbox_;
}
inline ::image_msg::bbox* one_detection::mutable_one_bbox() {
  // @@protoc_insertion_point(field_mutable:image_msg.one_detection.one_bbox)
  return _internal_mutable_one_bbox();
}
inline void one_detection::set_allocated_one_bbox(::image_msg::bbox* one_bbox) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete one_bbox_;
  }
  if (one_bbox) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(one_bbox);
    if (message_arena != submessage_arena) {
      one_bbox = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, one_bbox, submessage_arena);
    }
    
  } else {
    
  }
  one_bbox_ = one_bbox;
  // @@protoc_insertion_point(field_set_allocated:image_msg.one_detection.one_bbox)
}

// -------------------------------------------------------------------

// detections

// bool detected_flag = 1;
inline void detections::clear_detected_flag() {
  detected_flag_ = false;
}
inline bool detections::_internal_detected_flag() const {
  return detected_flag_;
}
inline bool detections::detected_flag() const {
  // @@protoc_insertion_point(field_get:image_msg.detections.detected_flag)
  return _internal_detected_flag();
}
inline void detections::_internal_set_detected_flag(bool value) {
  
  detected_flag_ = value;
}
inline void detections::set_detected_flag(bool value) {
  _internal_set_detected_flag(value);
  // @@protoc_insertion_point(field_set:image_msg.detections.detected_flag)
}

// repeated .image_msg.image image_ = 2;
inline int detections::_internal_image__size() const {
  return image__.size();
}
inline int detections::image__size() const {
  return _internal_image__size();
}
inline void detections::clear_image_() {
  image__.Clear();
}
inline ::image_msg::image* detections::mutable_image_(int index) {
  // @@protoc_insertion_point(field_mutable:image_msg.detections.image_)
  return image__.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image >*
detections::mutable_image_() {
  // @@protoc_insertion_point(field_mutable_list:image_msg.detections.image_)
  return &image__;
}
inline const ::image_msg::image& detections::_internal_image_(int index) const {
  return image__.Get(index);
}
inline const ::image_msg::image& detections::image_(int index) const {
  // @@protoc_insertion_point(field_get:image_msg.detections.image_)
  return _internal_image_(index);
}
inline ::image_msg::image* detections::_internal_add_image_() {
  return image__.Add();
}
inline ::image_msg::image* detections::add_image_() {
  // @@protoc_insertion_point(field_add:image_msg.detections.image_)
  return _internal_add_image_();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image >&
detections::image_() const {
  // @@protoc_insertion_point(field_list:image_msg.detections.image_)
  return image__;
}

// repeated .image_msg.one_detection detection = 3;
inline int detections::_internal_detection_size() const {
  return detection_.size();
}
inline int detections::detection_size() const {
  return _internal_detection_size();
}
inline void detections::clear_detection() {
  detection_.Clear();
}
inline ::image_msg::one_detection* detections::mutable_detection(int index) {
  // @@protoc_insertion_point(field_mutable:image_msg.detections.detection)
  return detection_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::one_detection >*
detections::mutable_detection() {
  // @@protoc_insertion_point(field_mutable_list:image_msg.detections.detection)
  return &detection_;
}
inline const ::image_msg::one_detection& detections::_internal_detection(int index) const {
  return detection_.Get(index);
}
inline const ::image_msg::one_detection& detections::detection(int index) const {
  // @@protoc_insertion_point(field_get:image_msg.detections.detection)
  return _internal_detection(index);
}
inline ::image_msg::one_detection* detections::_internal_add_detection() {
  return detection_.Add();
}
inline ::image_msg::one_detection* detections::add_detection() {
  // @@protoc_insertion_point(field_add:image_msg.detections.detection)
  return _internal_add_detection();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::one_detection >&
detections::detection() const {
  // @@protoc_insertion_point(field_list:image_msg.detections.detection)
  return detection_;
}

// -------------------------------------------------------------------

// image_buf

// repeated .image_msg.image image_ = 1;
inline int image_buf::_internal_image__size() const {
  return image__.size();
}
inline int image_buf::image__size() const {
  return _internal_image__size();
}
inline void image_buf::clear_image_() {
  image__.Clear();
}
inline ::image_msg::image* image_buf::mutable_image_(int index) {
  // @@protoc_insertion_point(field_mutable:image_msg.image_buf.image_)
  return image__.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image >*
image_buf::mutable_image_() {
  // @@protoc_insertion_point(field_mutable_list:image_msg.image_buf.image_)
  return &image__;
}
inline const ::image_msg::image& image_buf::_internal_image_(int index) const {
  return image__.Get(index);
}
inline const ::image_msg::image& image_buf::image_(int index) const {
  // @@protoc_insertion_point(field_get:image_msg.image_buf.image_)
  return _internal_image_(index);
}
inline ::image_msg::image* image_buf::_internal_add_image_() {
  return image__.Add();
}
inline ::image_msg::image* image_buf::add_image_() {
  // @@protoc_insertion_point(field_add:image_msg.image_buf.image_)
  return _internal_add_image_();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::image_msg::image >&
image_buf::image_() const {
  // @@protoc_insertion_point(field_list:image_msg.image_buf.image_)
  return image__;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace image_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_image_5fmsg_2eproto
